ControleTarefas/Models/ErrorViewModel.cs
namespace ControleTarefas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControleTarefas/Models/TarefaModel.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ControleTarefas.Models
{
    [Table("Tarefas")]
    public class TarefasModel
    {

        public int ID { get; set; }
        public string Nome { get; set; } = string.Empty;
        public string Tarefa { get; set; } = string.Empty;
        public int StatusTarefa { get; set; } = 0;
    }
}

ControleTarefas/Controllers/HomeController.cs
using ControleTarefas.Data;
using ControleTarefas.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace ControleTarefas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ControleTarefasContext _context;
        public HomeController(ControleTarefasContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return _context.TarefasModel != null ?
                        View(await _context.TarefasModel.ToListAsync()) :
                        Problem("Entity set 'ControleTarefasContext.TarefasModel'  is null.");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ControleTarefas/Controllers/TarefasModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ControleTarefas.Data;
using ControleTarefas.Models;

namespace ControleTarefas.Controllers
{
    public class TarefasModelsController : Controller
    {
        private readonly ControleTarefasContext _context;

        public TarefasModelsController(ControleTarefasContext context)
        {
            _context = context;
        }

        // GET: TarefasModels
        public async Task<IActionResult> Index()
        {
              return _context.TarefasModel != null ? 
                          View(await _context.TarefasModel.ToListAsync()) :
                          Problem("Entity set 'ControleTarefasContext.TarefasModel'  is null.");
        }

        // POST: TarefasModels
        [HttpPost]
        public async Task<IActionResult> Index(int id, [Bind("StatusTarefa")] TarefasModel tarefasModel)
        {
            if (id == null || _context.TarefasModel == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var tarefas = await _context.TarefasModel.FindAsync(id);
                    tarefas.StatusTarefa = 1;
                    _context.Update(tarefas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TarefasModelExists(tarefasModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tarefasModel);

        }

        // GET: TarefasModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TarefasModel == null)
            {
                return NotFound();
            }

            var tarefasModel = await _context.TarefasModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tarefasModel == null)
            {
                return NotFound();
            }

            return View(tarefasModel);
        }

        // GET: TarefasModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TarefasModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nome,Tarefa")] TarefasModel tarefasModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tarefasModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tarefasModel);
        }

        // GET: TarefasModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TarefasModel == null)
            {
                return NotFound();
            }

            var tarefasModel = await _context.TarefasModel.FindAsync(id);
            if (tarefasModel == null)
            {
                return NotFound();
            }
            return View(tarefasModel);
        }

        // POST: TarefasModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nome,Tarefa")] TarefasModel tarefasModel)
        {
            if (id != tarefasModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tarefasModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TarefasModelExists(tarefasModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tarefasModel);
        }

        // GET: TarefasModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TarefasModel == null)
            {
                return NotFound();
            }

            var tarefasModel = await _context.TarefasModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tarefasModel == null)
            {
                return NotFound();
            }

            return View(tarefasModel);
        }

        // POST: TarefasModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TarefasModel == null)
            {
                return Problem("Entity set 'ControleTarefasContext.TarefasModel'  is null.");
            }
            var tarefasModel = await _context.TarefasModel.FindAsync(id);
            if (tarefasModel != null)
            {
                _context.TarefasModel.Remove(tarefasModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TarefasModelExists(int id)
        {
          return (_context.TarefasModel?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

ControleTarefas/Views/Home/Index.cshtml
@model IEnumerable<ControleTarefas.Models.TarefasModel>
@{
    ViewData["Title"] = "Home Page";
}

<h1 class="d-flex justify-content-center p-3">Tarefas Concluidas</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tarefa)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if(item.StatusTarefa == 1)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tarefa)
                    </td>
                    <td class="ml-2">
                        <a type="button" asp-controller="TarefasModels" asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">Apagar</a>
                        <a type="button" asp-controller="TarefasModels" asp-action="Details" asp-route-id="@item.ID" class="btn btn-info">Detalhes</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

ControleTarefas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle Tarefas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ControleTarefas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">Controle de Tarefas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Tarefas Concluidas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TarefasModels" asp-action="Create">Criar Tarefa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TarefasModels" asp-action="Index">Lista de Tarefas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Desenvolvido por Camilla & Thiago</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ControleTarefas/Views/TarefasModels/Create.cshtml
@model ControleTarefas.Models.TarefasModel

@{
    ViewData["Title"] = "Create";
}

<h1 class="d-flex justify-content-center">Comece a criar sua tarefa</h1>

<hr />
<div class="d-flex justify-content-center">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label h3 mb-auto mt-4">Título</label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tarefa" class="control-label form-label h5 mb-auto mt-4">Tarefa</label>
                <textarea asp-for="Tarefa" class="form-control" id="exampleFormControlTextarea1" rows="10"></textarea>
                <span asp-validation-for="Tarefa" class="text-danger"></span>
            </div>
            <div class="p-3 text-center form-group">
                <input type="submit" value="Criar" class="btn btn-primary w-25" />
                <a class="btn btn-secondary mx-2 w-25" onclick="limparCaixa()">Limpar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    function limparCaixa() {
        // Seleciona a caixa de texto pelo ID
        var caixaDeTexto = document.getElementById('exampleFormControlTextarea1');

        // Define o conteúdo da caixa de texto como vazio
        caixaDeTexto.value = '';
    }
</script>

ControleTarefas/Views/TarefasModels/Delete.cshtml
@model ControleTarefas.Models.TarefasModel

@{
    ViewData["Title"] = "Deletar tarefas";
}

<h3>Tem certeza que deseja excluir esta tarefa?</h3>
<div>
    <hr />
    <h4>Tarefa</h4>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tarefa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tarefa)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> 
        <a asp-action="Index" type="button" class="btn btn-secondary">Voltar</a>
    </form>
</div>

ControleTarefas/Views/TarefasModels/Details.cshtml
@model ControleTarefas.Models.TarefasModel

@{
    ViewData["Title"] = "Details";
}

<h1>Informações</h1>

<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tarefa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tarefa)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID" class="btn btn-primary">Editar</a> 
    <a asp-action="Index" type="button" class="btn btn-secondary">Voltar</a>
</div>

ControleTarefas/Views/TarefasModels/Edit.cshtml
@model ControleTarefas.Models.TarefasModel

@{
    ViewData["Title"] = "Edit";
}

<h1 class="d-flex justify-content-center">Editar Tarefa</h1>
<hr />
<div class="d-flex justify-content-center">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label">Título</label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tarefa" class="control-label"></label>
                <input asp-for="Tarefa" class="form-control" />
                <span asp-validation-for="Tarefa" class="text-danger"></span>
            </div>
            <div class="p-3 text-center form-group">
                <button type="submit" value="Save" class="btn btn-primary">Salvar</button>
                <a asp-action="Index" type="button" class="btn btn-secondary">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ControleTarefas/Views/TarefasModels/Index.cshtml
@model IEnumerable<ControleTarefas.Models.TarefasModel>

@{
    ViewData["Title"] = "Index";
}

<h1 class="d-flex justify-content-center p-3">Lista de Tarefas</h1>

<p>
    <a type="button" asp-action="Create" class="btn btn-primary">Criar nova tarefa</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tarefa)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
<form asp-action="Index">
@foreach (var item in Model) {
    if(item.StatusTarefa == 0)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tarefa)
            </td>
            <td class="ml-2">
                <a type="button" asp-action="Edit" asp-route-id="@item.ID" class="btn btn-primary">Editar</a>
                <a type="button" asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">Apagar</a>
                <a type="button" asp-action="Details" asp-route-id="@item.ID" class="btn btn-info">Detalhes</a>
                <button type="submit" value="Save" asp-route-id="@item.ID" class="btn btn-success">Concluído</button>
            </td>
        </tr>
    }
}
</form>
    </tbody>
</table>